name: rubygem

on:
  push:
    branches: ["development"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby 3.1.1
        # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
        # change this to (see https://github.com/ruby/setup-ruby#versioning):
        # uses: ruby/setup-ruby@v1
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          ruby-version: 3.1.1

      - name: Publish to GPR
        run: |
          sudo apt-get update -qq && \
          sudo apt install -y --no-install-recommends apt-transport-https git curl zip build-essential ragel fftw3-dev liblapacke-dev libyaml-dev minisat+
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:github: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          bundle install
          rake compile
          rake gem nmatrix_plugins=lapacke,fftw
          cd pkg/ && \
          gem push --KEY github --host https://rubygems.pkg.github.com/${OWNER} *.gem
        env:
          GEM_HOST_API_KEY: "Bearer ${{secrets.GITHUB_TOKEN}}"
          OWNER: ${{ github.repository_owner }}
